/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author acer
 */
public class ActualizarAdmins extends javax.swing.JFrame {

    /**
     * Creates new form ActualizarAdmins
     */
    public ActualizarAdmins() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        txtCerrar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Cedula = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        Apellidos = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        txtNombre1 = new javax.swing.JLabel();
        txtDocumento1 = new javax.swing.JLabel();
        txtapeliidos = new javax.swing.JLabel();
        txtPassword = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(246, 246, 251));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(0, 102, 102));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 190, 40));

        jSeparator2.setBackground(new java.awt.Color(0, 102, 102));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 190, 40));

        jSeparator3.setBackground(new java.awt.Color(0, 102, 102));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 190, 40));

        jSeparator4.setBackground(new java.awt.Color(0, 102, 102));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 190, 30));

        txtCerrar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtCerrar.setText("X");
        txtCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCerrarMouseClicked(evt);
            }
        });
        getContentPane().add(txtCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 20, -1));

        jPanel1.setBackground(new java.awt.Color(246, 246, 251));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cedula.setBackground(new java.awt.Color(246, 246, 251));
        Cedula.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Cedula.setBorder(null);
        jPanel1.add(Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 190, 30));

        Nombre.setBackground(new java.awt.Color(246, 246, 251));
        Nombre.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Nombre.setBorder(null);
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 190, 30));

        Apellidos.setBackground(new java.awt.Color(246, 246, 251));
        Apellidos.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Apellidos.setBorder(null);
        jPanel1.add(Apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 190, 30));

        password.setBackground(new java.awt.Color(246, 246, 251));
        password.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        password.setBorder(null);
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 190, 30));

        txtNombre1.setText("Nombre");
        jPanel1.add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        txtDocumento1.setText("Cedula");
        jPanel1.add(txtDocumento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        txtapeliidos.setText("Apellidos");
        jPanel1.add(txtapeliidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        txtPassword.setText("Password");
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        btnActualizar.setBackground(new java.awt.Color(0, 102, 102));
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(null);
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 150, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void txtCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_txtCerrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarAdmins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarAdmins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarAdmins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarAdmins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarAdmins().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Apellidos;
    public javax.swing.JTextField Cedula;
    public javax.swing.JTextField Nombre;
    public javax.swing.JButton btnActualizar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    public javax.swing.JPasswordField password;
    public javax.swing.JLabel txtCerrar;
    private javax.swing.JLabel txtDocumento1;
    private javax.swing.JLabel txtNombre1;
    private javax.swing.JLabel txtPassword;
    private javax.swing.JLabel txtapeliidos;
    // End of variables declaration//GEN-END:variables
}
