/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import com.pascualbravo.models.Conexion;
import com.pascualbravo.models.CrudServicios;
import com.pascualbravo.models.Servicios;
import java.awt.Image;
import java.awt.event.ItemEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class FrmServicios extends javax.swing.JFrame {

    Conexion conexion = new Conexion();
    CrudServicios crudServicios = new CrudServicios();
    Servicios servicios = new Servicios();

    public FrmServicios() {
        initComponents();

        cbxEncargadoServicios = conexion.llenarCbx(cbxEncargadoServicios, "Nombre", "Empleados");
        cbxTipoLavadoServicios = conexion.llenarCbx(cbxTipoLavadoServicios, "TIpo_Servicio", "servicios");

        ImageIcon imgEditar = new ImageIcon("src\\Recursos\\boligrafo.png");
        editarPrecioServicio.setIcon(new ImageIcon(imgEditar.getImage().getScaledInstance(editarPrecioServicio.getWidth(), editarPrecioServicio.getHeight(), Image.SCALE_SMOOTH)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cancelarServicio = new javax.swing.JButton();
        btnConfirmarServicio = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txtPlacaVehiculo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtTelefonoCliente = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        editarPrecioServicio = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMarcaVehiculo = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        txtNombreVehiculo = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        txtModeloVehiculo = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        txtColorVehiculo = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        txtCedulaCliente = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        cbxTipoLavadoServicios = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        cbxEncargadoServicios = new javax.swing.JComboBox<>();
        txtPrecioServicio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(246, 246, 251));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancelarServicio.setBackground(new java.awt.Color(0, 153, 204));
        cancelarServicio.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        cancelarServicio.setForeground(new java.awt.Color(0, 0, 0));
        cancelarServicio.setText("Cancelar");
        cancelarServicio.setBorder(null);
        cancelarServicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarServicioActionPerformed(evt);
            }
        });
        jPanel2.add(cancelarServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 160, 50));

        btnConfirmarServicio.setBackground(new java.awt.Color(0, 153, 204));
        btnConfirmarServicio.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        btnConfirmarServicio.setForeground(new java.awt.Color(0, 0, 0));
        btnConfirmarServicio.setText("Confirmar");
        btnConfirmarServicio.setBorder(null);
        btnConfirmarServicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnConfirmarServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 480, 180, 50));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 220, 10));

        txtPlacaVehiculo.setBackground(new java.awt.Color(246, 246, 251));
        txtPlacaVehiculo.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        txtPlacaVehiculo.setForeground(new java.awt.Color(0, 0, 0));
        txtPlacaVehiculo.setBorder(null);
        txtPlacaVehiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPlacaVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaVehiculoActionPerformed(evt);
            }
        });
        jPanel2.add(txtPlacaVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 220, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Nombre");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 120, 30));

        txtNombreCliente.setBackground(new java.awt.Color(246, 246, 251));
        txtNombreCliente.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        txtNombreCliente.setForeground(new java.awt.Color(0, 0, 0));
        txtNombreCliente.setBorder(null);
        txtNombreCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreClienteActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 240, 30));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 240, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Teléfono de contacto");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 220, 30));

        txtTelefonoCliente.setBackground(new java.awt.Color(246, 246, 251));
        txtTelefonoCliente.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        txtTelefonoCliente.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefonoCliente.setBorder(null);
        txtTelefonoCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTelefonoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoClienteActionPerformed(evt);
            }
        });
        jPanel2.add(txtTelefonoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 290, 30));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 290, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 80)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("$");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, -1, 80));

        editarPrecioServicio.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        editarPrecioServicio.setForeground(new java.awt.Color(0, 0, 0));
        editarPrecioServicio.setText("(Incono editar)");
        editarPrecioServicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editarPrecioServicio.setPreferredSize(new java.awt.Dimension(70, 70));
        editarPrecioServicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarPrecioServicioMouseClicked(evt);
            }
        });
        jPanel2.add(editarPrecioServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Placa");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 90, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Servicio");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 100, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Datos del vehiculo");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 260, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Datos del Cliente");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 320, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("Marca");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 90, 30));

        txtMarcaVehiculo.setBackground(new java.awt.Color(246, 246, 251));
        txtMarcaVehiculo.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        txtMarcaVehiculo.setForeground(new java.awt.Color(0, 0, 0));
        txtMarcaVehiculo.setBorder(null);
        txtMarcaVehiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtMarcaVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaVehiculoActionPerformed(evt);
            }
        });
        jPanel2.add(txtMarcaVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 230, 30));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 230, 10));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Nombre");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 90, 30));

        txtNombreVehiculo.setBackground(new java.awt.Color(246, 246, 251));
        txtNombreVehiculo.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        txtNombreVehiculo.setForeground(new java.awt.Color(0, 0, 0));
        txtNombreVehiculo.setBorder(null);
        txtNombreVehiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNombreVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreVehiculoActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombreVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 260, 30));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 260, 10));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("Modelo");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 90, 30));

        txtModeloVehiculo.setBackground(new java.awt.Color(246, 246, 251));
        txtModeloVehiculo.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        txtModeloVehiculo.setForeground(new java.awt.Color(0, 0, 0));
        txtModeloVehiculo.setBorder(null);
        txtModeloVehiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtModeloVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloVehiculoActionPerformed(evt);
            }
        });
        jPanel2.add(txtModeloVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 110, 30));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 110, 10));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Color");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 90, 40));

        txtColorVehiculo.setBackground(new java.awt.Color(246, 246, 251));
        txtColorVehiculo.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        txtColorVehiculo.setForeground(new java.awt.Color(0, 0, 0));
        txtColorVehiculo.setBorder(null);
        txtColorVehiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtColorVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorVehiculoActionPerformed(evt);
            }
        });
        jPanel2.add(txtColorVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 120, 30));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 130, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("Tipo de lavado");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 180, 170, 30));

        txtCedulaCliente.setBackground(new java.awt.Color(246, 246, 251));
        txtCedulaCliente.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        txtCedulaCliente.setForeground(new java.awt.Color(0, 0, 0));
        txtCedulaCliente.setBorder(null);
        txtCedulaCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCedulaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaClienteActionPerformed(evt);
            }
        });
        jPanel2.add(txtCedulaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 250, 30));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 250, 10));

        jLabel15.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("Cedula");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 120, 30));

        cbxTipoLavadoServicios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona" }));
        cbxTipoLavadoServicios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxTipoLavadoServiciosItemStateChanged(evt);
            }
        });
        jPanel2.add(cbxTipoLavadoServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, 240, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setText("Encargado");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, 120, 30));

        cbxEncargadoServicios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona" }));
        cbxEncargadoServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEncargadoServiciosActionPerformed(evt);
            }
        });
        jPanel2.add(cbxEncargadoServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, 210, 30));

        txtPrecioServicio.setBackground(new java.awt.Color(246, 246, 251));
        txtPrecioServicio.setFont(new java.awt.Font("Segoe UI Light", 1, 80)); // NOI18N
        txtPrecioServicio.setForeground(new java.awt.Color(0, 0, 0));
        txtPrecioServicio.setText("0.0");
        txtPrecioServicio.setBorder(null);
        txtPrecioServicio.setEnabled(false);
        jPanel2.add(txtPrecioServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 370, 90));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1060, 580));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarServicioActionPerformed

    private void txtPlacaVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaVehiculoActionPerformed

    private void txtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreClienteActionPerformed

    private void txtTelefonoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoClienteActionPerformed

    private void txtMarcaVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaVehiculoActionPerformed

    private void txtNombreVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreVehiculoActionPerformed

    private void txtModeloVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloVehiculoActionPerformed

    private void txtColorVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorVehiculoActionPerformed

    private void txtCedulaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaClienteActionPerformed

    private void cbxEncargadoServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEncargadoServiciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEncargadoServiciosActionPerformed

    private void cbxTipoLavadoServiciosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxTipoLavadoServiciosItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            servicios = crudServicios.buscarServicio(cbxTipoLavadoServicios.getSelectedItem().toString());
            txtPrecioServicio.setText(String.valueOf(servicios.getValor()));
        }
    }//GEN-LAST:event_cbxTipoLavadoServiciosItemStateChanged

    private void editarPrecioServicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarPrecioServicioMouseClicked

        txtPrecioServicio.setText(JOptionPane.showInputDialog(null, "Ingrese un nuevo valor para el servico"));
    }//GEN-LAST:event_editarPrecioServicioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmServicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnConfirmarServicio;
    private javax.swing.JButton cancelarServicio;
    public javax.swing.JComboBox<String> cbxEncargadoServicios;
    public javax.swing.JComboBox<String> cbxTipoLavadoServicios;
    private javax.swing.JLabel editarPrecioServicio;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    public javax.swing.JTextField txtCedulaCliente;
    public javax.swing.JTextField txtColorVehiculo;
    public javax.swing.JTextField txtMarcaVehiculo;
    public javax.swing.JTextField txtModeloVehiculo;
    public javax.swing.JTextField txtNombreCliente;
    public javax.swing.JTextField txtNombreVehiculo;
    public javax.swing.JTextField txtPlacaVehiculo;
    public javax.swing.JTextField txtPrecioServicio;
    public javax.swing.JTextField txtTelefonoCliente;
    // End of variables declaration//GEN-END:variables
}
