/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Image;
import javax.swing.ImageIcon;

public class listaEmpleados extends javax.swing.JFrame {

   
    public listaEmpleados() {
        initComponents();
        ImageIcon imgBuscar = new ImageIcon("src\\Recursos\\buscar.png");
        lblBuscar.setIcon(new ImageIcon(imgBuscar.getImage().getScaledInstance(lblBuscar.getWidth(), lblBuscar.getHeight(), Image.SCALE_SMOOTH)));       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2 = new java.awt.Panel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jrbEmpleados = new javax.swing.JRadioButton();
        jrbClientes = new javax.swing.JRadioButton();
        panel1 = new java.awt.Panel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtListaEmp = new javax.swing.JTable();
        txtJefe = new javax.swing.JTextField();
        TxtCedula = new javax.swing.JTextField();
        txtSalario = new javax.swing.JTextField();
        jlblJefe = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JlblSalario = new javax.swing.JLabel();
        btnBorrar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtBuscarCedula = new javax.swing.JTextField();
        lblBuscar = new javax.swing.JLabel();
        btnNuevoEmp = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(246, 246, 251));
        jPanel2.setPreferredSize(new java.awt.Dimension(1040, 550));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jrbEmpleados.setBackground(new java.awt.Color(0, 153, 204));
        jrbEmpleados.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jrbEmpleados.setForeground(new java.awt.Color(0, 0, 0));
        jrbEmpleados.setText("Empleados");
        jPanel2.add(jrbEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 220, 50));

        jrbClientes.setBackground(new java.awt.Color(0, 153, 204));
        jrbClientes.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jrbClientes.setForeground(new java.awt.Color(0, 0, 0));
        jrbClientes.setText("Clientes");
        jrbClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbClientesActionPerformed(evt);
            }
        });
        jPanel2.add(jrbClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 170, 50));
        jPanel2.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        jtListaEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Cedula", "Salario", "Jefe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtListaEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtListaEmpMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtListaEmp);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 720, 390));

        txtJefe.setBackground(new java.awt.Color(246, 246, 251));
        txtJefe.setBorder(null);
        jPanel2.add(txtJefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 420, 230, -1));

        TxtCedula.setBackground(new java.awt.Color(246, 246, 251));
        TxtCedula.setBorder(null);
        TxtCedula.setEnabled(false);
        TxtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCedulaActionPerformed(evt);
            }
        });
        jPanel2.add(TxtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 280, 230, -1));

        txtSalario.setBackground(new java.awt.Color(246, 246, 251));
        txtSalario.setBorder(null);
        txtSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioActionPerformed(evt);
            }
        });
        jPanel2.add(txtSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 350, 230, -1));

        jlblJefe.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jlblJefe.setText("Jefe");
        jPanel2.add(jlblJefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 390, 70, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel2.setText("Nombre");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, 70, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel3.setText("Cedula");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 250, 70, -1));

        JlblSalario.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        JlblSalario.setText("Salario");
        jPanel2.add(JlblSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 320, 70, -1));

        btnBorrar.setBackground(new java.awt.Color(0, 153, 204));
        btnBorrar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(0, 0, 0));
        btnBorrar.setText("Borrar");
        btnBorrar.setBorder(null);
        btnBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 480, 100, 50));

        txtNombre.setBackground(new java.awt.Color(246, 246, 251));
        txtNombre.setBorder(null);
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 220, 220, -1));

        txtBuscarCedula.setBackground(new java.awt.Color(246, 246, 251));
        txtBuscarCedula.setBorder(null);
        jPanel2.add(txtBuscarCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 130, 20));

        lblBuscar.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        lblBuscar.setForeground(new java.awt.Color(0, 0, 0));
        lblBuscar.setText("(Incono editar)");
        lblBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBuscar.setPreferredSize(new java.awt.Dimension(70, 70));
        jPanel2.add(lblBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 50, 40));
        lblBuscar.getAccessibleContext().setAccessibleName("(Incono buscar)");

        btnNuevoEmp.setBackground(new java.awt.Color(0, 153, 204));
        btnNuevoEmp.setFont(new java.awt.Font("Segoe UI Semibold", 1, 32)); // NOI18N
        btnNuevoEmp.setForeground(new java.awt.Color(0, 0, 0));
        btnNuevoEmp.setText("Nuevo Empleado");
        btnNuevoEmp.setBorder(null);
        btnNuevoEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevoEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoEmpActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevoEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40, 260, 50));

        btnActualizar.setBackground(new java.awt.Color(0, 153, 204));
        btnActualizar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(0, 0, 0));
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(null);
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 480, 130, 50));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 140, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 440, 220, 10));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 242, 220, 10));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 300, 220, 10));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 370, 220, 10));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1060, 590));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -4, 1080, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jrbClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbClientesActionPerformed
     
    }//GEN-LAST:event_jrbClientesActionPerformed

    private void jtListaEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtListaEmpMouseClicked
       
    }//GEN-LAST:event_jtListaEmpMouseClicked

    private void txtSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalarioActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnNuevoEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoEmpActionPerformed

    private void TxtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCedulaActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed

     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listaEmpleados().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel JlblSalario;
    public javax.swing.JTextField TxtCedula;
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnBorrar;
    public javax.swing.JButton btnNuevoEmp;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    public javax.swing.JLabel jlblJefe;
    public javax.swing.JRadioButton jrbClientes;
    public javax.swing.JRadioButton jrbEmpleados;
    public javax.swing.JTable jtListaEmp;
    public javax.swing.JLabel lblBuscar;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    public javax.swing.JTextField txtBuscarCedula;
    public javax.swing.JTextField txtJefe;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables
}
